format = """
[](fg:#D91B4F)\
[](fg:#1A1C20 bg:#D91B4F)\
$directory\
[](fg:#1A1C20 bg:#D91B4F)\
[](fg:#D91B4F bg:#1A1C20)\
$git_branch\
$git_status\ 
$git_metrics\
[](fg:#1A1C20 bg:#D91B4F)\
[](fg:#D91B4F bg:#1A1C20)\
$time\
[](fg:#1A1C20 bg:#D91B4F)\
[](fg:#D91B4F bg:#1A1C20)\
$cmd_duration\
[](fg:#1A1C20 bg:#D91B4F)\
[](fg:#D91B4F)\
$character"""



[directory]
style = "fg:#04F2FB bg:#1A1C20"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "fg:green bg:#1A1C20 "
format = '[ $symbol $branch ]($style)'

[git_status]
format = '([\[$all_status$ahead_behind\] ]($style))'
style = "fg:green bg:#1A1C20"
conflicted = ''
up_to_date = '✓'
untracked = ''
stashed = ''
modified = ''
staged = '[++\($count\)](green)'
renamed = '󰙏'
deleted = ''
ahead = '⇡${count}'
diverged = '⇕⇡${ahead_count}⇣${behind_count}'
behind = '⇣${count}'

[git_metrics]
disabled = false
added_style = 'fg:bold blue bg:#1A1C20'
deleted_style = 'fg:bold blue bg:#1A1C20 '
format = '[+$added]($added_style)[|-$deleted ]($deleted_style)'

[git_state]
disabled = false
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ PICKING](bold red)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1A1C20"
format = '[[  $time ](fg:#EED2F3 bg:#1A1C20)]($style)'

[cmd_duration]
format = "[ $duration ]($style)"
style = "fg:#FD3EFC bg:#1A1C20"

[character]
success_symbol = "[]()"
error_symbol = "[ ](fg:#04F2FB)"

